# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 520e2546883517bd65bcfeb1af0eacc8b8e65dd48e6009a1512160cd5844b2b14f441d5709f9110717b248499be5c16167713dc74684da3e741061f331fc5cb4

test:
  secret_key_base: 8acad29240e12c93deb28641b6f36447bd340ce7e4769ab7717bd79f4ba15e534762d41fdad55fff8821d538f7a2c9149969ca1fcc8ed8649c13a41bcd8b284c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  production:
  sendgrid_username: w3afkli10
  sendgrid_password: Wormgb10
